### ISSUE TITLE
how to apply styles to collection

### ISSUE THREAD

**Issue by SplitterAlex** [pauloamgomes/ImageStyles#1]
Hello!

I am using your addon to extend the image api. It looks very good, but I got stuck at a certain point.

I can't figure out how I can apply the styles to my collection entrys.

I created a Collection called "test" with a single field called "imageField" with type "Image".
I also created a "ImageStyle" called "placeholder".

The next is to follow this step:

> For configuring an image field to have one or more styles automatically added it's only required to edit the field settings and add a "styles" attribute. When retrieving a collection that includes that image field, the corresponding image style URLs will be incorporated in the response:

I can't figure out where I can add a "styles" attribute to the field settings. Which field settings to you mean?

BTW: The related image link in your "readme.md" file doesn't work.
https://camo.githubusercontent.com/946d17fb11f3ac56e5011a1d44730e1f6e9efb94/68747470733a2f2f6d6f6e6f736e61702e636f6d2f66696c652f42384a3348464e417a613937325379693631313068526e786250424c6e662e706e67

Thank you for your help and implementing this addon!

Best regards Alex

**Comment by emdahlstrom** [comment]
Hi! Thank's for the great module! Same issue here, it's not clear to me how to add the styles attribute. Tried with { "styles": "hero" } but that didn't seem to work. What's the correct format?

All the best,
Em

**Comment by jesperlandberg** [comment]
Hi, seems like the module I need, however as two people have commented above, me neither can figure out how to add styles to image fields.

Added this to my field:
{
 "styles": [
     {
       "style": "Large"
     }
  ]
}

**Comment by SplitterAlex** [comment]
I figured it out:

For example for a Field-Type **Image** the JSON-Options should look like this:

```json
{
  "meta": {
    "title": {
      "type": "text",
      "label": "Title"
    }
  },
  "styles": [
    "placeholder",
    "xs",
    "sm",
    "medium",
    "large"
  ]
}
```

Where the entrys in array **styles** are the custom defined **Image Styles**

**Comment by pauloamgomes** [comment]
@jesperlandberg , did a new release that supports Set, Gallery and Repeater

**Comment by jesperlandberg** [comment]
@pauloamgomes amazing! thanks!

**Comment by igormigas** [comment]
Still have problems with setting this properly. After adding "styles" in JSON options I get structure like at the bottom and no result. No idea what can be wrong..
`{
"fields": {
"title": {},
"description": {},
"gallery": {
"name": "gallery",
"type": "gallery",
"localize": false,
"options": {
"styles": "cover"
}
}, (...)`

**Comment by pauloamgomes** [comment]
Did you resave your collection entries? something concerning in cockpit is that changes in collections will not reflect on the existing entries until you save them. Can you also put here the configuration of your field?

**Comment by igormigas** [comment]
This is the basic field configuration from API. Inside gallery and image I simply put `{ "styles": "name" }`.
I deleted all entries and created new dummies. The only thing I did not do was to delete whole collection.
```
{
  "fields": {
    "title": {
      "name": "title",
      "type": "text",
      "localize": false,
      "options": [
        
      ]
    },
    "description": {
      "name": "description",
      "type": "text",
      "localize": false,
      "options": [
        
      ]
    },
    "gallery": {
      "name": "gallery",
      "type": "gallery",
      "localize": false,
      "options": {
        "styles": "thumbnail"
      }
    },
    "image": {
      "name": "image",
      "type": "image",
      "localize": false,
      "options": {
        "styles": "cover"
      }
    }
  }
}
```

**Comment by pauloamgomes** [comment]
Yeah, your structure seems to be wrong, the styles shall be defined as below:

```
    "image": {
      "name": "image",
      "type": "image",
      "localize": false,
      "styles": [
        "cover"
      ]
```

**Comment by igormigas** [comment]
I know, but how to define it? Everything from JSON option will go to "options"..

**Comment by pauloamgomes** [comment]
Humm, not sure if we are on the same page, resuming, I expect that on the **field definition of your collection** you have something like:

```
{
  "meta": {
    "title": {
      "type": "image",
      "label": "image"
    }
  },
  "styles": [
    "cover"
  ]
}
```
after that if you create new entries and fetch the collection you'll receive something like:

```json
{
    "name": "Collection entry 1",
    "_by": "5a61396e7640edoc1261186187",
    "_created": 1520763462,
    "_id": "5aa5024609164doc2094391092",
    "_mby": "5a61396e7640edoc1261186187",
    "_modified": 1532386507,
    "image": {
        "path": "storage/uploads/2018/01/23/5a67b2b3542fbfire.jpg",
        "styles": [
            {
                "path": "http://default/storage/thumbs/929fac2255dbaa684e11a5acd174a50a_450x450_90_1532377833_thumbnail_adb115059e28d960fa8badfac5516667.jpg",
                "style": "Cover"
            }
        ]
    }
}
```

**Comment by igormigas** [comment]
Ok... we are probably not.
It is like my second day with Cockpit and the only way I've been creating collection was the UI, and you are probably talking about setting definition manually. If so then I need to dive deeper into Cockpit settings first.

Thanks for help anyway.

**Comment by pauloamgomes** [comment]
No, I created it manually using the UI, please confirm that you are using Cockpit latest version (0.6.1 / next). If you are, and you configured the field as I mentioned above you should have the same results as me.

**Comment by igormigas** [comment]
I have 0.6.1 version and this is all I can set: typical data and JSON options. Either my installation is corrupted or I am really tired and can't see simple things...

![image](https://user-images.githubusercontent.com/36771636/44267891-31a7a380-a230-11e8-829e-cd284ac8fee1.png)

**Comment by igormigas** [comment]
So eventually it was all about JSON options field. Now I get it.

I put everything according to your advices, but only Image type worked, Gallery did not change. So I decided to dive into `actions.php` and found out you put Image check in `switch` at the bottom as default. I did some tests and, at least for me, everything works if I change line 21:
```php
      switch ($field['type']) {
```
for this:
```php
      // Check if current field in entry is defined by user, I don't want '_id' etc. to proceed.
      if(!array_key_exists($fieldName, $fields)) {
        continue;
      }
      // Optionally check if current field is one of four special types
      // Without this, types like Date might end in switch default (although conditionals will stop them, because nobody will put "styles" there)
      if(!in_array($fields[$fieldName]['type'], ['repeater', 'set', 'gallery', 'image'])) {
        continue;
      }

      switch ($fields[$fieldName]['type']) {
```

I will treat this as a workaround for my problem.
Thanks again, your script helped me move forward with the project.

**Comment by pauloamgomes** [comment]
For gallery are you configuring the field like below?

```json
{
  "styles": [
    "cover"
  ]
}
```
But I'll take a better look and if your fix works happy if you can do a PR

**Comment by igormigas** [comment]
Yes, exactly like that.
I wrote you more details in the pull #3. After changing the variable in switch (and getting rid of $field alias) it works like a charm for me.
