### ISSUE TITLE
Problem with Encoded Base64 images

### ISSUE THREAD

**Issue by SplitterAlex** [pauloamgomes/ImageStyles#11]
When I set the output of an ImageStyle to _Base64 output_ the suffix **?cimgt=<CACHE_ID>** is added at the end of the output.

When using the generated output in an `<img>` tag an error is showing up in the browser console: **ERR_INVALID_URL**

```
<img src="data:image/jpg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD//gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4w...P3QhAfDZMAu7//Z?cimgt=1541476877"">
```

When I remove the suffix **?cimgt=<CACHE_ID** the image is correctly shown. Preferable the suffix should be omited on Base64 outputs.

**Comment by pauloamgomes** [comment]
Yeah, good catch. Should be fixed now.

**Comment by SplitterAlex** [comment]
It is fixed! Thank you!
