### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by andrevvm** [pauloamgomes/ImageStyles#12]
Looks like a great add-on, but getting page not found on a fresh install, using the latest Next branch from https://github.com/agentejo/cockpit.

The add-on shows in the dashboard, but once any of the links are visited a 404 is thrown.
<img width="1201" alt="screen shot 2018-11-26 at 2 47 37 pm" src="https://user-images.githubusercontent.com/742229/49046904-9311d380-f18a-11e8-89be-0f0eb4f4732f.png">

<img width="1005" alt="screen shot 2018-11-26 at 2 51 14 pm" src="https://user-images.githubusercontent.com/742229/49046970-c5233580-f18a-11e8-9fda-6ee2ac4922ae.png">

Is there a potential problem with my local configuration, or can this be replicated?

**Comment by pauloamgomes** [comment]
Hi @andrevvm , thanks for the catch, it seems the link was outdated. Fixed.

**Comment by andrevvm** [comment]
@pauloamgomes Thanks for the quick fix, awesome add-on!
