### ISSUE TITLE
Only Asset field returns correct path

### ISSUE THREAD

**Issue by andrevvm** [pauloamgomes/ImageStyles#14]
Bumping into another issue, hope that it is an easy fix! When using Gallery or Image fields, the Styles array is returning in the API response, but the path values aren't correct, see below for an example. 

```
{
  "meta": {
    "title": "",
    "asset": "5c25483431653218f6000081"
  },
  "path": "https://localhost:3000/admin/storage/uploads/2018/12/27/5c2548336931dP1110702.JPG",
  "cimgt": 1545950988,
  "styles": [
    {
      "style": "large",
      "path": "?cimgt=1545950988"
    }
  ]
}
```

Asset field has correct path:

```
"styles": [
  {
    "style": "large",
    "path": "storage/styles/process/5c1965ad31653207d8000145/f91659b84238a1cc8d231c7863d7ddd9_1280x1000_90_1545947190_bestFit_adb115059e28d960fa8badfac5516667.jpg?cimgt=1545950761"
  }
]
```

Please let me know if you're able to reproduce this, it seems to be the case for all attempts I've made. 

Thanks for all your help!

**Comment by pauloamgomes** [comment]
Hey @andrevvm, can you provide your field configuration for the gallery or image field? Is gallery configured with assets or images?

**Comment by andrevvm** [comment]
I wasn't aware gallery fields could be configured with asset fields! Didn't see it in https://getcockpit.com/documentation/reference/fieldtypes. That would solve my problem, as I don't _need_ it to be an image field. 

My field configuration is only defining the style needed. It works with an asset field, but not with an image field. I also noticed that asset fields will return all image styles without a configuration.

```
{
  "styles": [
    "cover"
  ]
}
```

**Comment by andrevvm** [comment]
@pauloamgomes thanks so much for your help on this. What is the configuration to use assets field with gallery?

**Comment by pauloamgomes** [comment]
It should be now fixed in the master branch, I tried a gallery with an asset an image and it worked for both and only for the configured styles.
