### ISSUE TITLE
Support for cloudstore asset

### ISSUE THREAD

**Issue by BitDron** [pauloamgomes/ImageStyles#17]
Hi,

Can work it with asset cloudstore and style cloudstore together ?

**Comment by pauloamgomes** [comment]
Hey @BitDron , what you mean by cloudstore?
The addon should support the providers from cloudstorage - https://github.com/agentejo/CloudStorage

**Comment by BitDron** [comment]
Sorry, I meant cloudstorage instead of cloudstore.

I have this config: 

`cloudstorage:
  styles:
    type: minio
    key: <KEY>
    secret: <SECRET>
    region: us-east-1
    bucket: bitdron
    prefix: styles
    endpoint: htttps://minio.example.com
    image_address: htttps://minio.example.com/bitdron/styles
`
it's work fine, styles are generated correctly in Minio Server. But with this configuration: 

`cloudstorage:
  styles:
    type: minio
    key: <KEY>
    secret: <SECRET>
    region: us-east-1
    bucket: bitdron
    prefix: styles
    endpoint: htttps://minio.example.com
    image_address: htttps://minio.example.com/bitdron/styles
  styles:
    type: minio
    key: <KEY>
    secret: <SECRET>
    region: us-east-1
    bucket: bitdron
    prefix: backend
    endpoint: htttps://minio.example.com
    image_address: htttps://minio.example.com/bitdron/backend
`

Assets are generated correctly in Minio Server, but styles don't

**Comment by pauloamgomes** [comment]
Never tested with Minio, just S3, in theory, it should work as I'm just relying on the cloudstorage addon.. so need to investigate further..  can you try with S3 to confirm that is not another issue?
