### ISSUE TITLE
Basic question: Outputting ImageStyles paths in Vue template

### ISSUE THREAD

**Issue by nickpish** [pauloamgomes/ImageStyles#18]
Hi, I'm relatively new to Cockpit/ImageStyles as well as Vue, and I'm working on a project in which I'd like to integrate the different image sizes into my templates, and I'm having issues getting the path to resolve properly. I have the ImageStyles addon installed and configured with a couple test image styles, "prj500w" and "prj850w" and the JSON response is as follows:

```
"entries": [
    {
      "published": true,
      "title": "Test image",
      "image": {
        "path": "/2019/04/22/5cbdfb6edb19dIMG_20181215_145012.jpg",
        "title": "IMG_20181215_145012.jpg",
        "mime": "image/jpeg",
        .
        .
        .
        "folder": "",
        "_id": "5cbdfb7030613678090002df",
        "styles": [
          {
            "style": "prj850w",
            "path": "storage/styles/posts/5cb3a6893662615069000357/4bd354151141a1944db471be40f48bf4_850x1134_90_1555954544_fitToWidth_adb115059e28d960fa8badfac5516667.jpg?cimgt=1555955158"
          },
          {
            "style": "prj500w",
            "path": "storage/styles/posts/5cb3a6893662615069000357/4eb94475a55e479b54a811da0fbf57a3_500x667_90_1555954544_fitToWidth_adb115059e28d960fa8badfac5516667.jpg?cimgt=1555955158"
          }
        ],
        "cimgt": 1555955158
      },
    }
]
```

I'm using Axios to handle the request, with `response.data.entries` as the response, so I can output `{{ post.title }}` or `post.image.path` in my template. However, I'm unsure how to get the path for the ImageStyles generated images. In my template code, I have:

```
<img v-if="post.image.path" :src="'http://mywebsite.com/cockpit/storage/uploads/' + post.image.path">
```
to output a basic image associated with a post, and I'm not sure how to edit the path such that it returns, for example, the corresponding "prj850w" path? Thanks for any assistance here- I realize this is a rather basic question.

**Comment by nickpish** [comment]
Just to provide an update here for anyone else who might have a similar question- I was able to output the image path in Vue as follows, referencing the returned (JSON) image styles array as follows:

```
<img v-if="post.image.styles" :src="'http://mywebsite.com/cockpit/' + post.image.styles[1].path">
```

This works, although I wish there were a way I could structure the JSON response and/or array such that I could reference the actual name of image style, e.g. "prj500w" instead of by the array index

**Comment by pauloamgomes** [comment]
@nickpish , usually what I do, is to have a function that receives the image object and the style and parses the object search for the style and if not found fallbacks to the default path, e.g.:


```
export function getImagePath(image, style) {
  const IMAGE_PATH = process.env.COCKPIT_API_ASSETS_URL;

  let url = image.path;

  if (style && image.styles !== undefined && image.styles.length) {
    const imageStyle = image.styles.find(styleObj => styleObj.style === style);

    if (imageStyle !== undefined) {
      url = imageStyle.path;
      if (!url.startsWith("/styles")) {
        url = `/styles${url}`;
      }
    }
  }

  return `${IMAGE_PATH}${url}`;
}
```

**Comment by nickpish** [comment]
@pauloamgomes Thanks for the response! Would you be able to provide an example of how one might use that function in a Vue template?

**Comment by pauloamgomes** [comment]
Sorry, I'm not familiar with Vue, but believe you can do something like below:

```
Vue.component('cockpitImage', {
  template:'<img :src="url">',
  data() {
    return {
    }
  },
  computed:{
    url:function() {
      // custom parsing of asset and return correct style path
    }
  },
  props:{
    width:{
      default:400
    },
    height:{
      default:400,
    }
  }
});
```

**Comment by nickpish** [comment]
Awesome, thanks @pauloamgomes I will give it a shot!
