### ISSUE TITLE
Wrong path output with custom storage path

### ISSUE THREAD

**Issue by va-studio** [pauloamgomes/ImageStyles#19]
Hi! We're trying to integrate this add-on with our installation of cockpit, which is configured with a custom storage path, but the output path is wrong:

`````
path: "/cms?cimgt=1557508356"
style: "medium"
`````

The image field configuration is the following:

`````
{
  "meta": {
    "title": {
      "type": "text",
      "label": "Title"
    }
  },
  "styles": [
    "medium"
  ]
}
``````

The add-on seems to create the styles folder, within the custom directory, but it only outputs a blank html file. 

Thank you

**Comment by pauloamgomes** [comment]
Hi @va-studio , a couple of questions:

1. Do you have any specific settings on the config.yaml for the site_url/base_route/media.path?
2. The configuration is for image or asset? The addon shall work on both situations but I recommend to use asset field instead of image one.
3. Can you provide the full json of the entry field?

**Comment by va-studio** [comment]
Hi @pauloamgomes, yes, we do have specific setting on the config.yaml document but maybe they're not correct, please see below:

`````
# Cockpit settings
i18n: en

languages:
    pt: Portuguese

groups:
    admin:
        $admin: true
        $vars:
            finder.path : /storage/media
            assets.path : /storage/assets

paths:
  "#storage": /Users/joaosousa/Sites/v-a/storage/
`````

As for the configuration, as you can see we're only using for "finder.path" and "assets.path", did I miss anything?

Also, the full json of the image field is:
`````
{
  cimgt:1557508712,
  meta: {
    title: "Caption":
  },
  path:"storage/media/ww-cover.jpg",
  styles: {
    0: {
      path: "1557508712",
      style: "medium"
    }
  }
}
`````

As I said, we set up cockpit with a custom storage folder and the root folders are the following:
- /cms (installation of cockpit)
- /storage (all the storage folders)
- /app (next.js)

Thanks again
