### ISSUE TITLE
Images losing EXIF data

### ISSUE THREAD

**Issue by staegi** [pauloamgomes/ImageStyles#21]
To be able to use such libraries like https://www.npmjs.com/package/react-exif-orientation-img to rotate images correctly in the frontend, this add-on should pass through the EXIF data of the images.

**Comment by pauloamgomes** [comment]
Hi @staegi , thanks for you comment. I understand the issue, but I'm using core cockpit functions to save the images:

```
$thumb = $this->app->module('cockpit')->thumbnail($options);
```

Think you should open an issue on Cockpit project, it uses the claviska\SimpleImage library to handle the resize of images, and also seem to be discussed on https://github.com/claviska/SimpleImage/issues/157

Tbh, I would prefer to have a different image manipulation library, but didn't had the time to change the image styles implementation.
