### ISSUE TITLE
Only use for base64 output -> how to avoid resizing?

### ISSUE THREAD

**Issue by tommueller** [pauloamgomes/ImageStyles#22]
I am planning on using this plugin only for using the base64-output option.
S I dont want to resize the image and add no styles. Adding no styles is not an issue, but the resizing always happens.

Anyway to avoid this? Thanks!

**Comment by pauloamgomes** [comment]
Hi @tommueller , the purpose of the image styles is exactly on providing multiple resized images of the image field. 

Did you tried to use the cockpit assets api for that or it has the same issue?

https://getcockpit.com/documentation/api/cockpit

<img width="809" alt="image" src="https://user-images.githubusercontent.com/102261/91185073-a3ebd200-e6ed-11ea-96fe-4100c019267a.png">

**Comment by tommueller** [comment]
No that one sadly also gives an `{"error":"Target width or height parameter is missing"}` if you don't specify any. That's why I had hoped that ImageStyles could help me out with this ...

**Comment by pauloamgomes** [comment]
In that case probably would not be possible to do it in image styles either, as I use the cockpit core thumbnail function and believe it requires the same parameters.

**Comment by tommueller** [comment]
Mmh, damn. Well then I will investigate other options. Thanks!
