### ISSUE TITLE
Styles not rebuilt

### ISSUE THREAD

**Issue by fabien** [pauloamgomes/ImageStyles#23]
I have a an image field with `"styles": ["thumbnail"]` ("thumbnail" style exists, too), I can see an '(trashcan) Image Styles' button and saving an entry will indeed add the correct data to the item.

However, I was under the impression that a collection's styles will be fully rebuilt automatically whenever such a field is set (or updated) - basically when the collection *definition* is changed. Looking at the code, it doesn't seem to be the case.

So I resorted to the CLI `./cp refresh-styles -name recipes` which appears to run successfully, yet it doesn't update the entries with the thumbnail data either. Any idea?

**Comment by fabien** [comment]
Update: the images have actually all been generated, it's the item's (meta) data that is not updated with the path info etc.

**Comment by pauloamgomes** [comment]
Thanks! Merged the PR, pls confirm it works now.

Keep in mind that addon was built a long time ago.. today I would recommend a different approach, maybe leveraging imgproxy - http://imgproxy.net

**Comment by fabien** [comment]
I can confirm it works with the changes made. Even if it's made a long time ago, for our purposes it seems to work nicely. Thanks!
