### ISSUE TITLE
How can I hide the ImageStyles Plugin in a specific user group?

### ISSUE THREAD

**Issue by diegozuber** [pauloamgomes/ImageStyles#4]
First: Thanks for your amazing work!

I'm successfully using the ImageStyles Plugin in Cockpit v0.6.2.

The only thing that disturbs me a bit is, that on each user group the ImageStyles Plugin shows in the Dashboard. Of course nobody can manage any of the rules, it's just a visual aspect. Can I hide that somehow in a specific user group.

Here a screenshots of the dashboard in the authors user group:
![bildschirmfoto 2018-08-29 um 14 29 42 pm](https://user-images.githubusercontent.com/21689209/44787945-ecbd2e80-ab98-11e8-9b25-21839d138a73.png)

**Comment by pauloamgomes** [comment]
Hey @diegozuber , need to recheck the ACLs for the dashboard, its displayed by default. I'll provide an update soon.

**Comment by pauloamgomes** [comment]
That should be now updated with the latest release, basically, only the admin or users with the ACL manage.admin or manage.view will have the imagestyles block in the dashboard. A typical case where the group authors can see the image styles but not configure them:

```yaml
groups:
    author:
        imagestyles:
            manage.view: true
            manage.admin: false 
```
