### ISSUE TITLE
ImageStyles doesnt work when we put it into repeater with set fields

### ISSUE THREAD

**Issue by Venikeee1** [pauloamgomes/ImageStyles#5]
Everything works fine but when i want to create repeater and place "set" field that contains image the styles url doesnt created. I got only path resived in the data

**Comment by popovfreewind** [comment]
yep, i have same problem.
Anyway, thanks for your plugin!

**Comment by popovfreewind** [comment]
Here is example of code what i put in repeter field options:
`
{
  "field": {
    "type": "set",
    "options": {
      "fields": [
        {
          "type": "image",
          "name": "image",
          "styles": [
            "team"
          ]
        },
        {
          "type": "text",
          "name": "title"
        }
      ]
    }
  }
}
`
and i get just path to original image.

**Comment by pauloamgomes** [comment]
Hey Guys, as said in the other issue, my approach is not accommodating nested levels like repeater > set, I'll need to look on it when I have few time.. if someone can help with a patch I'll appreciate it.

**Comment by pauloamgomes** [comment]
I did a quick update and images that are inside a Repeater > Set or Set > Repeater will have the styles generated. Probably will need to do some refactoring as don't like the current approach but its working.
