### ISSUE TITLE
Installation problems, suggestions for installation manual

### ISSUE THREAD

**Issue by jbjhjm** [pauloamgomes/ImageStyles#6]
Hi guys, I'm right now trying to make ImageStyles 1.5 run on latest Cockpit 0.7.2.
After following the installation guide I only got fatal errors.
This happened because of the addons folder name.
I suggest to add to the manual that the folder needs to exactly be namen "ImageStyles".

After that, I was able to see the ImageStyles Dashboard widget. However there's still nothing appearing in the menu. 

The widget behaviours seems weird too. If I click "create new", cockpit will show a 404 Error page. But if I click the plus sign in the widget's title bar, the editing layout will display - even though it's the same URL as the other link. 

Do you have any idea why this is happening and what's wrong?

Edit: I tested and all functionality works fine, though there's no item in the menu.

Thanks!

**Comment by pauloamgomes** [comment]
Hey @jbjhjm , thanks for your comment and sorry for late answer, you should move to the latest version of ImageStyles as some core functionalities have changed. Updated the installation notes to ensure that the folder name is mentioned.
