### ISSUE TITLE
Trailing slash missing in url/path for styles

### ISSUE THREAD

**Issue by SplitterAlex** [pauloamgomes/ImageStyles#9]
When using ImageStyles (tested with Image/Gallery) I am getting an unreasoned path for styles. The trailing slashes are missing.

For Example:

```json
"mainImage": {
  "path": "/storage/uploads/2018/11/06/5be11936e1850web-title-3.jpg",
  "cimgt": 1541481283,
  "styles": [
    {
      "style": "medium",
      "path": "storagestylesblog5be12343363164003400030e3eb8844d186c8b88f6f139ebe9e2da59_1000x668_40_1541478712_fitToWidth_adb115059e28d960fa8badfac5516667.jpg?cimgt=1541481283"
     },
     {
       "style": "large",
       "path": "storagestylesblog5be12343363164003400030e78fffbd3b25a7a0515959b5ce580cd03_1400x935_40_1541478712_fitToWidth_adb115059e28d960fa8badfac5516667.jpg?cimgt=1541481283"
      }
  ]
},
```
It should be:
```json
"path": "/storage/styles/blog/5be12343363164003400030e/3eb8844d186c8b88f6f139ebe9e2da59_1000x668_40_1541478712_fitToWidth_adb115059e28d960fa8badfac5516667.jpg?cimgt=1541481283"
```

**Environment:**
Cockpit: 0.8.3
ImageStyles: 1.7

**Comment by pauloamgomes** [comment]
Hi @SplitterAlex , can you try on the latest version? and also confirm your system settings as seems to be working well on my end!

**Comment by SplitterAlex** [comment]
Hello @pauloamgomes!

I tried version 1.8 but the trailing slashes are still missing. In fact the trailing slashes are for example also missing inside a Base64 Output of an image.

I run Cockpit.0.8.3 on Docker and I am using the official [Docker image for Cockpit](https://github.com/agentejo/cockpit-dockerl). Cockpit is running without any problems.

I am working on a Windows 10 Machine and I tried the same with a [WampServer](http://www.wampserver.com/en/) and I got this as a response:

```json
{
    "fields": {
        "image": {
            "name": "image",
            "type": "image",
            "localize": false,
            "options": {
                "styles": [
                    "placeholder",
                    "sm"
                ]
            }
        }
    },
    "entries": [
        {
            "image": {
                "path": "http://localhost/cockpit-8/storage/uploads/2018/11/06/5be1491d421b6mob-DSC05593.jpg",
                "cimgt": 1541490996,
                "styles": [
                    {
                        "style": "placeholder",
                        "path": "?cimgt=1541490996"
                    },
                    {
                        "style": "sm",
                        "path": "?cimgt=1541490996"
                    }
                ]
            },
            "_mby": "5be147253366631de400001e",
            "_by": "5be147253366631de400001e",
            "_modified": 1541490996,
            "_created": 1541490996,
            "_id": "5be149343366631de40002f3"
        }
    ],
    "total": 1
}
```

**Comment by pauloamgomes** [comment]
Can you confirm on a non-windows environment? Also what happens if you use the core cockpit api to get a thumbnail?

**Comment by SplitterAlex** [comment]
Hello

When I use the core cockpit api such as:


```json
POST: http://192.168.99.100:8080/api/cockpit/image?token=5d51306cf5ff825747f7d8518c012e
{
	"src": "5be68b7334383500120001a9",
	"m": "fitToWidth",
	"w": 1000,
	"h": 0,
	"q": 90,
	"d": false
}
----------------------------------------
I am getting this response:
http://192.168.99.100:8080/storage/thumbs/eacd446b837c4b43e250c4cb434b927d_1000x1500_90_1541835635_fitToWidth_adb115059e28d960fa8badfac5516667.jpg
```


I tried to run Cockpit on a DigitalOcean Droplet with Ubuntu 18 and Docker and the trailing slashes are still missing... This is so weird...
I tried ImageStyles source code versions 1.5/1.6 and they work just fine.

**Comment by SplitterAlex** [comment]
I tried all this http requests on my windows machine and on my ubuntu droplet and in both cases the trailing slashes are missing.

@pauloamgomes On which environment are you working?

**Comment by pauloamgomes** [comment]
Forget my last comment, didn't have check that you already tested against the cockpit core image api, just to resume:

1. Using the cockpit api, you receive the thumb url with slashes, correct?
2. Using the image styles you always receive without slashes.

**Comment by SplitterAlex** [comment]
Yes exactly that is the case.

**Comment by nliautaud** [comment]
Same here. Apache, PHP 7.2, Cockpit 0.8.3, latest plugin.

<img width="378" alt="capture d ecran 2018-11-14 a 19 30 46" src="https://user-images.githubusercontent.com/761761/48504211-7b5e5500-e844-11e8-8a91-73b3fd29edd3.png">

**Comment by pauloamgomes** [comment]
Hey Guys, should be fixed now on master. Probably you have a site_url or base_url configuration defined to "/" and that was causing the unexpected replacement on the code. Please confirm and thanks for reporting.

**Comment by SplitterAlex** [comment]
Hello @pauloamgomes 

Thank you very much. The slashes are back.

Sadly there is a new bug. The base path **"storage"** is missing. My path styles are looking now like this:

```json
{
   "style": "xs",
   "path": "/styles/portfolio/5be110673230610020000146/0e502c745d7ffab327ca05bce672338f_300x200_40_1541476319_fitToWidth_adb115059e28d960fa8badfac5516667.jpg?cimgt=1541476877"
}
```

The correct path should be:

```json
{
   "style": "xs",
   "path": "/storage/styles/portfolio/5be110673230610020000146/0e502c745d7ffab327ca05bce672338f_300x200_40_1541476319_fitToWidth_adb115059e28d960fa8badfac5516667.jpg?cimgt=1541476877"
}
```

**Comment by pauloamgomes** [comment]
Yeah, that was on purpose, the main idea was to hide the storage folder of the URL, that was for cases where you would not access the storage from cockpit but from the filesystem (symlink, shared folder, etc..). But thinking better on it (it would not work with domain output flag) I added it again, so it should be ok now.

**Comment by nliautaud** [comment]
Fixed indeed !

**Comment by SplitterAlex** [comment]
I tested my code base against the last master src. Everything works now :) Thank you for your help @pauloamgomes !
